services:
  spark-master:
    image: jupyter/pyspark-notebook:latest
    container_name: spark-master
    user: root
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./notebooks:/home/jovyan/work
    command: /usr/local/spark/bin/spark-class org.apache.spark.deploy.master.Master

  spark-worker:
    image: jupyter/pyspark-notebook:latest
    container_name: spark-worker
    user: root
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
    ports:
      - "8081:8081"
    volumes:
      - ./notebooks:/home/jovyan/work
    command: /usr/local/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077

  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyter-spark
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=password
    depends_on:
      - spark-master